server:
  port: 5002

spring:
  application:
    name: salon

  datasource:
    url: "jdbc:mysql://localhost:3306/salondb?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: $7090Ashok
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



  mail:
    host: smtp.gmail.com
    port: 587
    username: gedelashipa.1321@gmail.com
    password: rlxz dggl spmd byfd
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: read_only
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "USER"
    description: "USER API For Salon Booking System"
    version: "1.0.0"